# Generated by Django 5.2.8 on 2025-12-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("product_manager", "Product Manager"),
                    ("sales_manager", "Sales Manager"),
                    ("admin", "Administrator"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
