# Generated by Django 5.2.8 on 2026-01-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('product_manager', 'Product Manager'), ('sales_manager', 'Sales Manager'), ('support_manager', 'Support Manager'), ('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
