# Generated by Django 4.2.26 on 2026-01-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax identification number', max_length=50),
        ),
    ]
