# Generated by Django 5.2.8 on 2025-12-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
