# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_orderitem_order_delete_order_delete_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_sales_emails",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user wants to receive sales/promotional emails",
            ),
        ),
    ]

