# Generated by Django 4.2.26 on 2026-01-12 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to agents'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the response', max_length=200)),
                ('content', models.TextField(help_text='Response content')),
                ('category', models.CharField(blank=True, help_text="Category (e.g., 'Order', 'Refund', 'Technical')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this response has been used')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canned Response',
                'verbose_name_plural': 'Canned Responses',
                'ordering': ['-usage_count', 'title'],
            },
        ),
    ]
