# Generated by Django 4.2.26 on 2026-01-05 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product_manager_api",
            "0005_remove_order_product_id_remove_order_product_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_end_date",
            field=models.DateTimeField(
                blank=True, help_text="When discount ends", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount percentage (0-100)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_start_date",
            field=models.DateTimeField(
                blank=True, help_text="When discount starts", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price before discount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=50)),
                ("user_email", models.EmailField(db_index=True, max_length=254)),
                ("product_id", models.IntegerField(db_index=True)),
                ("product_name", models.CharField(max_length=200)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-added_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "product_id"],
                        name="product_man_user_id_7781ff_idx",
                    ),
                    models.Index(
                        fields=["product_id"], name="product_man_product_80fb91_idx"
                    ),
                ],
                "unique_together": {("user_id", "product_id")},
            },
        ),
    ]
