# Generated by Django 5.2.8 on 2025-12-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_api', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_manager_api.category'),
        ),
    ]
