# Generated by Django 5.2.8 on 2025-12-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_api', '0006_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
