# Generated by Django 5.2.8 on 2025-12-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager_api', '0007_product_old_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_category',
        ),
    ]
